/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import CSDL.Database;
import Model.SanPham;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguyentienthuan
 */
public class frqlsanpham extends javax.swing.JFrame {

    /**
     * Creates new form frqlsanpham
     */
    public frqlsanpham() {
        initComponents();
        HienThiDSSP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        options = new javax.swing.JComboBox<>();
        btthongke = new javax.swing.JButton();
        btthem = new javax.swing.JButton();
        btsua = new javax.swing.JButton();
        btxoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbsp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sản phẩm");

        jLabel1.setText("Nhóm sản phẩm: ");

        options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả sản phẩm", "Hoa Đà Lạt", "Hoa sinh nhật", "Hoa cưới" }));

        btthongke.setText("Thống kê");
        btthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthongkeActionPerformed(evt);
            }
        });

        btthem.setText("Thêm");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        btsua.setText("Sửa");
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });

        btxoa.setText("Xóa");
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });

        tbsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaSP", "TenSP", "HinhanhSP", "GioithieuSP", "GiaSP"
            }
        ));
        jScrollPane1.setViewportView(tbsp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btthongke)
                        .addGap(18, 18, 18)
                        .addComponent(btthem)
                        .addGap(18, 18, 18)
                        .addComponent(btsua)
                        .addGap(18, 18, 18)
                        .addComponent(btxoa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btthongke)
                    .addComponent(btthem)
                    .addComponent(btsua)
                    .addComponent(btxoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthongkeActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(this, );
    }//GEN-LAST:event_btthongkeActionPerformed

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        // TODO add your handling code here:
        frthemsp themsp = new frthemsp();
        themsp.qlsp=this;
        themsp.setVisible(true);
    }//GEN-LAST:event_btthemActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        // TODO add your handling code here:
        int i =this.tbsp.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng cần xóa");
            return;
        }
        DefaultTableModel model = (DefaultTableModel)this.tbsp.getModel();
        int masp=(int) model.getValueAt(i, 0);
        Database cn = new Database();
        int kq=cn.Xoasp(masp);
        if(kq>0){
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            HienThiDSSP();
        }
        else
            JOptionPane.showMessageDialog(this, "Lỗi xóa san pham");
    }//GEN-LAST:event_btxoaActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        // TODO add your handling code here:
        int i =this.tbsp.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng cần sửa");
            return;
        }
        else{
            SanPham sp = new SanPham();
            sp.masp=(int)tbsp.getModel().getValueAt(i,0);
            sp.tensp=(String)tbsp.getModel().getValueAt(i,1);
            sp.hinhanhsp=(String)tbsp.getModel().getValueAt(i,2);
            sp.gioithieusp=(String)tbsp.getModel().getValueAt(i,3);
            sp.giasp=(int)tbsp.getModel().getValueAt(i,4);
            frsuasp suasp = new frsuasp();
            suasp.sanpham=sp;
            suasp.qlsp=this;
            suasp.setVisible(true);
        }
        
    }//GEN-LAST:event_btsuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frqlsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frqlsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frqlsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frqlsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frqlsanpham().setVisible(true);
            }
        });
    }
    public void  HienThiDSSP(){
        Database qlsp = new Database();
        Vector<SanPham> dsSP=qlsp.DSSanPham();
        if(!dsSP.isEmpty()){
            DefaultTableModel dtm = (DefaultTableModel)tbsp.getModel();
            dtm.setRowCount(0);
            for(SanPham sp : dsSP)
            {
             dtm.addRow(new Object[]{sp.getMasp(),sp.getTensp(),sp.getHinhanhsp(),sp.getGioithieusp(),sp.getGiasp()});
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton btthongke;
    private javax.swing.JButton btxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> options;
    private javax.swing.JTable tbsp;
    // End of variables declaration//GEN-END:variables
}
